### ISSUE TITLE
non zawa entities cant be captured

### ISSUE THREAD

**Issue by doDidums** [ZAWA-Evolved/ZAWA#18]
for some reason only zawa entities can be captured with zawa items unlike before where anything could be captured

**Comment by Mnesikos** [comment]
This is not a bug, it's intentional. The capture net and slingshot net are only used for animals of specific sizes (thus, only zawa entities), however the capture cage and seine net will work on all animals- vanilla included. Read the wiki page on it here: <https://github.com/ZAWA-Evolved/ZAWA/wiki/Animal-capture>
