### ISSUE TITLE
[BUG] Scientific name not showing on some animals

### ISSUE THREAD

**Issue by raininavada** [ZAWA-Evolved/ZAWA#3]
So when I use the animal data book on any of the next animals: _Flamingo, Giraffe, Hornbill, Macaw, Spider Monkey_, the scientific name does not show up. Instead it shows an id, like for example for the giraffe it's "scientific.zawa.giraffe" It's the same for the ones I mentioned like "scientific.zawa.macaw".

All the other animals except fishes, brown rat, praying mantis, butterflies, tarantula and scorpions show their scientific name. I'm not sure if the fishes and insects/arthropods I just mentioned don't show scientific names on purpose but I wanted to point that out.

![2022-03-01_16 55 00](https://user-images.githubusercontent.com/100724695/156239133-dd3be89a-b057-4ccd-9a30-0cc1d7ead90f.png)

 - Minecraft 1.16.5
 - Forge 36.2.29
 - ZAWA Evolved Beta
 - Only optifine installed

(edit 1: removed imgur link edit 2: fixed some mistakes)

**Comment by Mnesikos** [comment]
Aha, I knew I was forgetting an instance of this somewhere!! Thank you for the report.

The first group of animals are our species variant animals, so instead of all of them sharing the same scientific name, each one has a different one. I just forgot it showed up on this particular page for them! Lol

As for the second group of animals, those are the ambients. They function entirely different from the full ZAWA animals, and thus intentionally do not have the extra info on their pages.

**Comment by Mnesikos** [comment]
Just fixed this in our dev space! Will be seen in version **1.0.0-BeefBeta3**, thanks again for reporting. ❤️
